// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CalcEvent interface {
	IsCalcEvent()
	GetID() string
	GetTimestamp() string
}

type CalculatorState struct {
	DisplayValue string   `json:"displayValue"`
	StoredValue  *float64 `json:"storedValue,omitempty"`
	CurrentOp    *string  `json:"currentOp,omitempty"`
	IsNewInput   bool     `json:"isNewInput"`
}

type Cleared struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
}

func (Cleared) IsCalcEvent()              {}
func (this Cleared) GetID() string        { return this.ID }
func (this Cleared) GetTimestamp() string { return this.Timestamp }

type DigitEntered struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Digit     string `json:"digit"`
}

func (DigitEntered) IsCalcEvent()              {}
func (this DigitEntered) GetID() string        { return this.ID }
func (this DigitEntered) GetTimestamp() string { return this.Timestamp }

type EqualsPressed struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
}

func (EqualsPressed) IsCalcEvent()              {}
func (this EqualsPressed) GetID() string        { return this.ID }
func (this EqualsPressed) GetTimestamp() string { return this.Timestamp }

type Mutation struct {
}

type OperatorSelected struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Operator  string `json:"operator"`
}

func (OperatorSelected) IsCalcEvent()              {}
func (this OperatorSelected) GetID() string        { return this.ID }
func (this OperatorSelected) GetTimestamp() string { return this.Timestamp }

type Query struct {
}

type Subscription struct {
}
