// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CalcEvent interface {
	IsCalcEvent()
	GetID() string
	GetTimestamp() string
}

type Calculated struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Result    string `json:"result"`
}

func (Calculated) IsCalcEvent()              {}
func (this Calculated) GetID() string        { return this.ID }
func (this Calculated) GetTimestamp() string { return this.Timestamp }

type CalculatorState struct {
	DisplayValue string   `json:"displayValue"`
	StoredValue  *float64 `json:"storedValue,omitempty"`
	CurrentOp    *string  `json:"currentOp,omitempty"`
	IsNewInput   bool     `json:"isNewInput"`
}

type Cleared struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
}

func (Cleared) IsCalcEvent()              {}
func (this Cleared) GetID() string        { return this.ID }
func (this Cleared) GetTimestamp() string { return this.Timestamp }

type DigitEntered struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Digit     Digit  `json:"digit"`
}

func (DigitEntered) IsCalcEvent()              {}
func (this DigitEntered) GetID() string        { return this.ID }
func (this DigitEntered) GetTimestamp() string { return this.Timestamp }

type Mutation struct {
}

type OperatorSelected struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Operator  string `json:"operator"`
}

func (OperatorSelected) IsCalcEvent()              {}
func (this OperatorSelected) GetID() string        { return this.ID }
func (this OperatorSelected) GetTimestamp() string { return this.Timestamp }

type Query struct {
}

type Subscription struct {
}

type Undone struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
}

func (Undone) IsCalcEvent()              {}
func (this Undone) GetID() string        { return this.ID }
func (this Undone) GetTimestamp() string { return this.Timestamp }

type Digit string

const (
	DigitZero  Digit = "ZERO"
	DigitOne   Digit = "ONE"
	DigitTwo   Digit = "TWO"
	DigitThree Digit = "THREE"
	DigitFour  Digit = "FOUR"
	DigitFive  Digit = "FIVE"
	DigitSix   Digit = "SIX"
	DigitSeven Digit = "SEVEN"
	DigitEight Digit = "EIGHT"
	DigitNine  Digit = "NINE"
	DigitDot   Digit = "DOT"
)

var AllDigit = []Digit{
	DigitZero,
	DigitOne,
	DigitTwo,
	DigitThree,
	DigitFour,
	DigitFive,
	DigitSix,
	DigitSeven,
	DigitEight,
	DigitNine,
	DigitDot,
}

func (e Digit) IsValid() bool {
	switch e {
	case DigitZero, DigitOne, DigitTwo, DigitThree, DigitFour, DigitFive, DigitSix, DigitSeven, DigitEight, DigitNine, DigitDot:
		return true
	}
	return false
}

func (e Digit) String() string {
	return string(e)
}

func (e *Digit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Digit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Digit", str)
	}
	return nil
}

func (e Digit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Digit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Digit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
