// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: calc/v1/events.proto

package calcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Digit int32

const (
	Digit_DIGIT_UNSPECIFIED Digit = 0
	Digit_DIGIT_ZERO        Digit = 1
	Digit_DIGIT_ONE         Digit = 2
	Digit_DIGIT_TWO         Digit = 3
	Digit_DIGIT_THREE       Digit = 4
	Digit_DIGIT_FOUR        Digit = 5
	Digit_DIGIT_FIVE        Digit = 6
	Digit_DIGIT_SIX         Digit = 7
	Digit_DIGIT_SEVEN       Digit = 8
	Digit_DIGIT_EIGHT       Digit = 9
	Digit_DIGIT_NINE        Digit = 10
	Digit_DIGIT_DOT         Digit = 11
)

// Enum value maps for Digit.
var (
	Digit_name = map[int32]string{
		0:  "DIGIT_UNSPECIFIED",
		1:  "DIGIT_ZERO",
		2:  "DIGIT_ONE",
		3:  "DIGIT_TWO",
		4:  "DIGIT_THREE",
		5:  "DIGIT_FOUR",
		6:  "DIGIT_FIVE",
		7:  "DIGIT_SIX",
		8:  "DIGIT_SEVEN",
		9:  "DIGIT_EIGHT",
		10: "DIGIT_NINE",
		11: "DIGIT_DOT",
	}
	Digit_value = map[string]int32{
		"DIGIT_UNSPECIFIED": 0,
		"DIGIT_ZERO":        1,
		"DIGIT_ONE":         2,
		"DIGIT_TWO":         3,
		"DIGIT_THREE":       4,
		"DIGIT_FOUR":        5,
		"DIGIT_FIVE":        6,
		"DIGIT_SIX":         7,
		"DIGIT_SEVEN":       8,
		"DIGIT_EIGHT":       9,
		"DIGIT_NINE":        10,
		"DIGIT_DOT":         11,
	}
)

func (x Digit) Enum() *Digit {
	p := new(Digit)
	*p = x
	return p
}

func (x Digit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Digit) Descriptor() protoreflect.EnumDescriptor {
	return file_calc_v1_events_proto_enumTypes[0].Descriptor()
}

func (Digit) Type() protoreflect.EnumType {
	return &file_calc_v1_events_proto_enumTypes[0]
}

func (x Digit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Digit.Descriptor instead.
func (Digit) EnumDescriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{0}
}

type DigitEntered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digit         Digit                  `protobuf:"varint,1,opt,name=digit,proto3,enum=calc.v1.Digit" json:"digit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitEntered) Reset() {
	*x = DigitEntered{}
	mi := &file_calc_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitEntered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitEntered) ProtoMessage() {}

func (x *DigitEntered) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitEntered.ProtoReflect.Descriptor instead.
func (*DigitEntered) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *DigitEntered) GetDigit() Digit {
	if x != nil {
		return x.Digit
	}
	return Digit_DIGIT_UNSPECIFIED
}

type OperatorSelected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorSelected) Reset() {
	*x = OperatorSelected{}
	mi := &file_calc_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorSelected) ProtoMessage() {}

func (x *OperatorSelected) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorSelected.ProtoReflect.Descriptor instead.
func (*OperatorSelected) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorSelected) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type Calculated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculated) Reset() {
	*x = Calculated{}
	mi := &file_calc_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculated) ProtoMessage() {}

func (x *Calculated) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculated.ProtoReflect.Descriptor instead.
func (*Calculated) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *Calculated) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Cleared struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cleared) Reset() {
	*x = Cleared{}
	mi := &file_calc_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cleared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cleared) ProtoMessage() {}

func (x *Cleared) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cleared.ProtoReflect.Descriptor instead.
func (*Cleared) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{3}
}

type Undone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Undone) Reset() {
	*x = Undone{}
	mi := &file_calc_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Undone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Undone) ProtoMessage() {}

func (x *Undone) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Undone.ProtoReflect.Descriptor instead.
func (*Undone) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{4}
}

type CalcEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CalcEvent_DigitEntered
	//	*CalcEvent_OperatorSelected
	//	*CalcEvent_Calculated
	//	*CalcEvent_Cleared
	//	*CalcEvent_Undone
	Event         isCalcEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcEvent) Reset() {
	*x = CalcEvent{}
	mi := &file_calc_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcEvent) ProtoMessage() {}

func (x *CalcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcEvent.ProtoReflect.Descriptor instead.
func (*CalcEvent) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *CalcEvent) GetEvent() isCalcEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CalcEvent) GetDigitEntered() *DigitEntered {
	if x != nil {
		if x, ok := x.Event.(*CalcEvent_DigitEntered); ok {
			return x.DigitEntered
		}
	}
	return nil
}

func (x *CalcEvent) GetOperatorSelected() *OperatorSelected {
	if x != nil {
		if x, ok := x.Event.(*CalcEvent_OperatorSelected); ok {
			return x.OperatorSelected
		}
	}
	return nil
}

func (x *CalcEvent) GetCalculated() *Calculated {
	if x != nil {
		if x, ok := x.Event.(*CalcEvent_Calculated); ok {
			return x.Calculated
		}
	}
	return nil
}

func (x *CalcEvent) GetCleared() *Cleared {
	if x != nil {
		if x, ok := x.Event.(*CalcEvent_Cleared); ok {
			return x.Cleared
		}
	}
	return nil
}

func (x *CalcEvent) GetUndone() *Undone {
	if x != nil {
		if x, ok := x.Event.(*CalcEvent_Undone); ok {
			return x.Undone
		}
	}
	return nil
}

type isCalcEvent_Event interface {
	isCalcEvent_Event()
}

type CalcEvent_DigitEntered struct {
	DigitEntered *DigitEntered `protobuf:"bytes,1,opt,name=digit_entered,json=digitEntered,proto3,oneof"`
}

type CalcEvent_OperatorSelected struct {
	OperatorSelected *OperatorSelected `protobuf:"bytes,2,opt,name=operator_selected,json=operatorSelected,proto3,oneof"`
}

type CalcEvent_Calculated struct {
	Calculated *Calculated `protobuf:"bytes,3,opt,name=calculated,proto3,oneof"`
}

type CalcEvent_Cleared struct {
	Cleared *Cleared `protobuf:"bytes,4,opt,name=cleared,proto3,oneof"`
}

type CalcEvent_Undone struct {
	Undone *Undone `protobuf:"bytes,5,opt,name=undone,proto3,oneof"`
}

func (*CalcEvent_DigitEntered) isCalcEvent_Event() {}

func (*CalcEvent_OperatorSelected) isCalcEvent_Event() {}

func (*CalcEvent_Calculated) isCalcEvent_Event() {}

func (*CalcEvent_Cleared) isCalcEvent_Event() {}

func (*CalcEvent_Undone) isCalcEvent_Event() {}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersistenceId string                 `protobuf:"bytes,1,opt,name=persistence_id,json=persistenceId,proto3" json:"persistence_id,omitempty"`
	SeqNr         int64                  `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Event         *CalcEvent             `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_calc_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventEnvelope) GetPersistenceId() string {
	if x != nil {
		return x.PersistenceId
	}
	return ""
}

func (x *EventEnvelope) GetSeqNr() int64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *EventEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventEnvelope) GetEvent() *CalcEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type CalculatorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayValue  string                 `protobuf:"bytes,1,opt,name=display_value,json=displayValue,proto3" json:"display_value,omitempty"`
	StoredValue   *float64               `protobuf:"fixed64,2,opt,name=stored_value,json=storedValue,proto3,oneof" json:"stored_value,omitempty"`
	CurrentOp     *string                `protobuf:"bytes,3,opt,name=current_op,json=currentOp,proto3,oneof" json:"current_op,omitempty"`
	IsNewInput    bool                   `protobuf:"varint,4,opt,name=is_new_input,json=isNewInput,proto3" json:"is_new_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatorState) Reset() {
	*x = CalculatorState{}
	mi := &file_calc_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorState) ProtoMessage() {}

func (x *CalculatorState) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorState.ProtoReflect.Descriptor instead.
func (*CalculatorState) Descriptor() ([]byte, []int) {
	return file_calc_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *CalculatorState) GetDisplayValue() string {
	if x != nil {
		return x.DisplayValue
	}
	return ""
}

func (x *CalculatorState) GetStoredValue() float64 {
	if x != nil && x.StoredValue != nil {
		return *x.StoredValue
	}
	return 0
}

func (x *CalculatorState) GetCurrentOp() string {
	if x != nil && x.CurrentOp != nil {
		return *x.CurrentOp
	}
	return ""
}

func (x *CalculatorState) GetIsNewInput() bool {
	if x != nil {
		return x.IsNewInput
	}
	return false
}

var File_calc_v1_events_proto protoreflect.FileDescriptor

const file_calc_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x14calc/v1/events.proto\x12\acalc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\fDigitEntered\x12$\n" +
	"\x05digit\x18\x01 \x01(\x0e2\x0e.calc.v1.DigitR\x05digit\".\n" +
	"\x10OperatorSelected\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\"$\n" +
	"\n" +
	"Calculated\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\t\n" +
	"\aCleared\"\b\n" +
	"\x06Undone\"\xac\x02\n" +
	"\tCalcEvent\x12<\n" +
	"\rdigit_entered\x18\x01 \x01(\v2\x15.calc.v1.DigitEnteredH\x00R\fdigitEntered\x12H\n" +
	"\x11operator_selected\x18\x02 \x01(\v2\x19.calc.v1.OperatorSelectedH\x00R\x10operatorSelected\x125\n" +
	"\n" +
	"calculated\x18\x03 \x01(\v2\x13.calc.v1.CalculatedH\x00R\n" +
	"calculated\x12,\n" +
	"\acleared\x18\x04 \x01(\v2\x10.calc.v1.ClearedH\x00R\acleared\x12)\n" +
	"\x06undone\x18\x05 \x01(\v2\x0f.calc.v1.UndoneH\x00R\x06undoneB\a\n" +
	"\x05event\"\xb1\x01\n" +
	"\rEventEnvelope\x12%\n" +
	"\x0epersistence_id\x18\x01 \x01(\tR\rpersistenceId\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x03R\x05seqNr\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x05event\x18\x04 \x01(\v2\x12.calc.v1.CalcEventR\x05event\"\xc4\x01\n" +
	"\x0fCalculatorState\x12#\n" +
	"\rdisplay_value\x18\x01 \x01(\tR\fdisplayValue\x12&\n" +
	"\fstored_value\x18\x02 \x01(\x01H\x00R\vstoredValue\x88\x01\x01\x12\"\n" +
	"\n" +
	"current_op\x18\x03 \x01(\tH\x01R\tcurrentOp\x88\x01\x01\x12 \n" +
	"\fis_new_input\x18\x04 \x01(\bR\n" +
	"isNewInputB\x0f\n" +
	"\r_stored_valueB\r\n" +
	"\v_current_op*\xcd\x01\n" +
	"\x05Digit\x12\x15\n" +
	"\x11DIGIT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"DIGIT_ZERO\x10\x01\x12\r\n" +
	"\tDIGIT_ONE\x10\x02\x12\r\n" +
	"\tDIGIT_TWO\x10\x03\x12\x0f\n" +
	"\vDIGIT_THREE\x10\x04\x12\x0e\n" +
	"\n" +
	"DIGIT_FOUR\x10\x05\x12\x0e\n" +
	"\n" +
	"DIGIT_FIVE\x10\x06\x12\r\n" +
	"\tDIGIT_SIX\x10\a\x12\x0f\n" +
	"\vDIGIT_SEVEN\x10\b\x12\x0f\n" +
	"\vDIGIT_EIGHT\x10\t\x12\x0e\n" +
	"\n" +
	"DIGIT_NINE\x10\n" +
	"\x12\r\n" +
	"\tDIGIT_DOT\x10\vB(Z&dentaku-bff/internal/pb/calc/v1;calcv1b\x06proto3"

var (
	file_calc_v1_events_proto_rawDescOnce sync.Once
	file_calc_v1_events_proto_rawDescData []byte
)

func file_calc_v1_events_proto_rawDescGZIP() []byte {
	file_calc_v1_events_proto_rawDescOnce.Do(func() {
		file_calc_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calc_v1_events_proto_rawDesc), len(file_calc_v1_events_proto_rawDesc)))
	})
	return file_calc_v1_events_proto_rawDescData
}

var file_calc_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calc_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_calc_v1_events_proto_goTypes = []any{
	(Digit)(0),                    // 0: calc.v1.Digit
	(*DigitEntered)(nil),          // 1: calc.v1.DigitEntered
	(*OperatorSelected)(nil),      // 2: calc.v1.OperatorSelected
	(*Calculated)(nil),            // 3: calc.v1.Calculated
	(*Cleared)(nil),               // 4: calc.v1.Cleared
	(*Undone)(nil),                // 5: calc.v1.Undone
	(*CalcEvent)(nil),             // 6: calc.v1.CalcEvent
	(*EventEnvelope)(nil),         // 7: calc.v1.EventEnvelope
	(*CalculatorState)(nil),       // 8: calc.v1.CalculatorState
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_calc_v1_events_proto_depIdxs = []int32{
	0, // 0: calc.v1.DigitEntered.digit:type_name -> calc.v1.Digit
	1, // 1: calc.v1.CalcEvent.digit_entered:type_name -> calc.v1.DigitEntered
	2, // 2: calc.v1.CalcEvent.operator_selected:type_name -> calc.v1.OperatorSelected
	3, // 3: calc.v1.CalcEvent.calculated:type_name -> calc.v1.Calculated
	4, // 4: calc.v1.CalcEvent.cleared:type_name -> calc.v1.Cleared
	5, // 5: calc.v1.CalcEvent.undone:type_name -> calc.v1.Undone
	9, // 6: calc.v1.EventEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	6, // 7: calc.v1.EventEnvelope.event:type_name -> calc.v1.CalcEvent
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_calc_v1_events_proto_init() }
func file_calc_v1_events_proto_init() {
	if File_calc_v1_events_proto != nil {
		return
	}
	file_calc_v1_events_proto_msgTypes[5].OneofWrappers = []any{
		(*CalcEvent_DigitEntered)(nil),
		(*CalcEvent_OperatorSelected)(nil),
		(*CalcEvent_Calculated)(nil),
		(*CalcEvent_Cleared)(nil),
		(*CalcEvent_Undone)(nil),
	}
	file_calc_v1_events_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calc_v1_events_proto_rawDesc), len(file_calc_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calc_v1_events_proto_goTypes,
		DependencyIndexes: file_calc_v1_events_proto_depIdxs,
		EnumInfos:         file_calc_v1_events_proto_enumTypes,
		MessageInfos:      file_calc_v1_events_proto_msgTypes,
	}.Build()
	File_calc_v1_events_proto = out.File
	file_calc_v1_events_proto_goTypes = nil
	file_calc_v1_events_proto_depIdxs = nil
}
