// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: calc/v1/read_service.proto

package calcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StateQueryService_GetState_FullMethodName = "/calc.v1.StateQueryService/GetState"
)

// StateQueryServiceClient is the client API for StateQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateQueryServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
}

type stateQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateQueryServiceClient(cc grpc.ClientConnInterface) StateQueryServiceClient {
	return &stateQueryServiceClient{cc}
}

func (c *stateQueryServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, StateQueryService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateQueryServiceServer is the server API for StateQueryService service.
// All implementations must embed UnimplementedStateQueryServiceServer
// for forward compatibility.
type StateQueryServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	mustEmbedUnimplementedStateQueryServiceServer()
}

// UnimplementedStateQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateQueryServiceServer struct{}

func (UnimplementedStateQueryServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedStateQueryServiceServer) mustEmbedUnimplementedStateQueryServiceServer() {}
func (UnimplementedStateQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeStateQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateQueryServiceServer will
// result in compilation errors.
type UnsafeStateQueryServiceServer interface {
	mustEmbedUnimplementedStateQueryServiceServer()
}

func RegisterStateQueryServiceServer(s grpc.ServiceRegistrar, srv StateQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedStateQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateQueryService_ServiceDesc, srv)
}

func _StateQueryService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateQueryServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateQueryService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateQueryServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateQueryService_ServiceDesc is the grpc.ServiceDesc for StateQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.v1.StateQueryService",
	HandlerType: (*StateQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _StateQueryService_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc/v1/read_service.proto",
}

const (
	StateStreamService_Subscribe_FullMethodName = "/calc.v1.StateStreamService/Subscribe"
)

// StateStreamServiceClient is the client API for StateStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateStreamServiceClient interface {
	Subscribe(ctx context.Context, in *StateStreamServiceSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateStreamServiceSubscribeResponse], error)
}

type stateStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateStreamServiceClient(cc grpc.ClientConnInterface) StateStreamServiceClient {
	return &stateStreamServiceClient{cc}
}

func (c *stateStreamServiceClient) Subscribe(ctx context.Context, in *StateStreamServiceSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateStreamServiceSubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateStreamService_ServiceDesc.Streams[0], StateStreamService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateStreamServiceSubscribeRequest, StateStreamServiceSubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateStreamService_SubscribeClient = grpc.ServerStreamingClient[StateStreamServiceSubscribeResponse]

// StateStreamServiceServer is the server API for StateStreamService service.
// All implementations must embed UnimplementedStateStreamServiceServer
// for forward compatibility.
type StateStreamServiceServer interface {
	Subscribe(*StateStreamServiceSubscribeRequest, grpc.ServerStreamingServer[StateStreamServiceSubscribeResponse]) error
	mustEmbedUnimplementedStateStreamServiceServer()
}

// UnimplementedStateStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateStreamServiceServer struct{}

func (UnimplementedStateStreamServiceServer) Subscribe(*StateStreamServiceSubscribeRequest, grpc.ServerStreamingServer[StateStreamServiceSubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedStateStreamServiceServer) mustEmbedUnimplementedStateStreamServiceServer() {}
func (UnimplementedStateStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeStateStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateStreamServiceServer will
// result in compilation errors.
type UnsafeStateStreamServiceServer interface {
	mustEmbedUnimplementedStateStreamServiceServer()
}

func RegisterStateStreamServiceServer(s grpc.ServiceRegistrar, srv StateStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStateStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateStreamService_ServiceDesc, srv)
}

func _StateStreamService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateStreamServiceSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateStreamServiceServer).Subscribe(m, &grpc.GenericServerStream[StateStreamServiceSubscribeRequest, StateStreamServiceSubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateStreamService_SubscribeServer = grpc.ServerStreamingServer[StateStreamServiceSubscribeResponse]

// StateStreamService_ServiceDesc is the grpc.ServiceDesc for StateStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.v1.StateStreamService",
	HandlerType: (*StateStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _StateStreamService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calc/v1/read_service.proto",
}
