// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: calc/v1/read_service.proto

package calcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_calc_v1_read_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_read_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_read_service_proto_rawDescGZIP(), []int{0}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *CalculatorState       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_calc_v1_read_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_read_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_read_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateResponse) GetState() *CalculatorState {
	if x != nil {
		return x.State
	}
	return nil
}

type StateStreamServiceSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateStreamServiceSubscribeRequest) Reset() {
	*x = StateStreamServiceSubscribeRequest{}
	mi := &file_calc_v1_read_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateStreamServiceSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateStreamServiceSubscribeRequest) ProtoMessage() {}

func (x *StateStreamServiceSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_read_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateStreamServiceSubscribeRequest.ProtoReflect.Descriptor instead.
func (*StateStreamServiceSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_read_service_proto_rawDescGZIP(), []int{2}
}

type StateStreamServiceSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *CalculatorState       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateStreamServiceSubscribeResponse) Reset() {
	*x = StateStreamServiceSubscribeResponse{}
	mi := &file_calc_v1_read_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateStreamServiceSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateStreamServiceSubscribeResponse) ProtoMessage() {}

func (x *StateStreamServiceSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_read_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateStreamServiceSubscribeResponse.ProtoReflect.Descriptor instead.
func (*StateStreamServiceSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_read_service_proto_rawDescGZIP(), []int{3}
}

func (x *StateStreamServiceSubscribeResponse) GetState() *CalculatorState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_calc_v1_read_service_proto protoreflect.FileDescriptor

const file_calc_v1_read_service_proto_rawDesc = "" +
	"\n" +
	"\x1acalc/v1/read_service.proto\x12\acalc.v1\x1a\x14calc/v1/events.proto\"\x11\n" +
	"\x0fGetStateRequest\"B\n" +
	"\x10GetStateResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.calc.v1.CalculatorStateR\x05state\"$\n" +
	"\"StateStreamServiceSubscribeRequest\"U\n" +
	"#StateStreamServiceSubscribeResponse\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.calc.v1.CalculatorStateR\x05state2T\n" +
	"\x11StateQueryService\x12?\n" +
	"\bGetState\x12\x18.calc.v1.GetStateRequest\x1a\x19.calc.v1.GetStateResponse2~\n" +
	"\x12StateStreamService\x12h\n" +
	"\tSubscribe\x12+.calc.v1.StateStreamServiceSubscribeRequest\x1a,.calc.v1.StateStreamServiceSubscribeResponse0\x01B(Z&dentaku-bff/internal/pb/calc/v1;calcv1b\x06proto3"

var (
	file_calc_v1_read_service_proto_rawDescOnce sync.Once
	file_calc_v1_read_service_proto_rawDescData []byte
)

func file_calc_v1_read_service_proto_rawDescGZIP() []byte {
	file_calc_v1_read_service_proto_rawDescOnce.Do(func() {
		file_calc_v1_read_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calc_v1_read_service_proto_rawDesc), len(file_calc_v1_read_service_proto_rawDesc)))
	})
	return file_calc_v1_read_service_proto_rawDescData
}

var file_calc_v1_read_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calc_v1_read_service_proto_goTypes = []any{
	(*GetStateRequest)(nil),                     // 0: calc.v1.GetStateRequest
	(*GetStateResponse)(nil),                    // 1: calc.v1.GetStateResponse
	(*StateStreamServiceSubscribeRequest)(nil),  // 2: calc.v1.StateStreamServiceSubscribeRequest
	(*StateStreamServiceSubscribeResponse)(nil), // 3: calc.v1.StateStreamServiceSubscribeResponse
	(*CalculatorState)(nil),                     // 4: calc.v1.CalculatorState
}
var file_calc_v1_read_service_proto_depIdxs = []int32{
	4, // 0: calc.v1.GetStateResponse.state:type_name -> calc.v1.CalculatorState
	4, // 1: calc.v1.StateStreamServiceSubscribeResponse.state:type_name -> calc.v1.CalculatorState
	0, // 2: calc.v1.StateQueryService.GetState:input_type -> calc.v1.GetStateRequest
	2, // 3: calc.v1.StateStreamService.Subscribe:input_type -> calc.v1.StateStreamServiceSubscribeRequest
	1, // 4: calc.v1.StateQueryService.GetState:output_type -> calc.v1.GetStateResponse
	3, // 5: calc.v1.StateStreamService.Subscribe:output_type -> calc.v1.StateStreamServiceSubscribeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_calc_v1_read_service_proto_init() }
func file_calc_v1_read_service_proto_init() {
	if File_calc_v1_read_service_proto != nil {
		return
	}
	file_calc_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calc_v1_read_service_proto_rawDesc), len(file_calc_v1_read_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_calc_v1_read_service_proto_goTypes,
		DependencyIndexes: file_calc_v1_read_service_proto_depIdxs,
		MessageInfos:      file_calc_v1_read_service_proto_msgTypes,
	}.Build()
	File_calc_v1_read_service_proto = out.File
	file_calc_v1_read_service_proto_goTypes = nil
	file_calc_v1_read_service_proto_depIdxs = nil
}
