// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: calc/v1/write_service.proto

package calcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandService_PressDigit_FullMethodName    = "/calc.v1.CommandService/PressDigit"
	CommandService_PressOperator_FullMethodName = "/calc.v1.CommandService/PressOperator"
	CommandService_PressEquals_FullMethodName   = "/calc.v1.CommandService/PressEquals"
	CommandService_PressClear_FullMethodName    = "/calc.v1.CommandService/PressClear"
	CommandService_PressUndo_FullMethodName     = "/calc.v1.CommandService/PressUndo"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandServiceClient interface {
	PressDigit(ctx context.Context, in *PressDigitRequest, opts ...grpc.CallOption) (*PressDigitResponse, error)
	PressOperator(ctx context.Context, in *PressOperatorRequest, opts ...grpc.CallOption) (*PressOperatorResponse, error)
	PressEquals(ctx context.Context, in *PressEqualsRequest, opts ...grpc.CallOption) (*PressEqualsResponse, error)
	PressClear(ctx context.Context, in *PressClearRequest, opts ...grpc.CallOption) (*PressClearResponse, error)
	PressUndo(ctx context.Context, in *PressUndoRequest, opts ...grpc.CallOption) (*PressUndoResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) PressDigit(ctx context.Context, in *PressDigitRequest, opts ...grpc.CallOption) (*PressDigitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressDigitResponse)
	err := c.cc.Invoke(ctx, CommandService_PressDigit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) PressOperator(ctx context.Context, in *PressOperatorRequest, opts ...grpc.CallOption) (*PressOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressOperatorResponse)
	err := c.cc.Invoke(ctx, CommandService_PressOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) PressEquals(ctx context.Context, in *PressEqualsRequest, opts ...grpc.CallOption) (*PressEqualsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressEqualsResponse)
	err := c.cc.Invoke(ctx, CommandService_PressEquals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) PressClear(ctx context.Context, in *PressClearRequest, opts ...grpc.CallOption) (*PressClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressClearResponse)
	err := c.cc.Invoke(ctx, CommandService_PressClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) PressUndo(ctx context.Context, in *PressUndoRequest, opts ...grpc.CallOption) (*PressUndoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressUndoResponse)
	err := c.cc.Invoke(ctx, CommandService_PressUndo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
type CommandServiceServer interface {
	PressDigit(context.Context, *PressDigitRequest) (*PressDigitResponse, error)
	PressOperator(context.Context, *PressOperatorRequest) (*PressOperatorResponse, error)
	PressEquals(context.Context, *PressEqualsRequest) (*PressEqualsResponse, error)
	PressClear(context.Context, *PressClearRequest) (*PressClearResponse, error)
	PressUndo(context.Context, *PressUndoRequest) (*PressUndoResponse, error)
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) PressDigit(context.Context, *PressDigitRequest) (*PressDigitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PressDigit not implemented")
}
func (UnimplementedCommandServiceServer) PressOperator(context.Context, *PressOperatorRequest) (*PressOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PressOperator not implemented")
}
func (UnimplementedCommandServiceServer) PressEquals(context.Context, *PressEqualsRequest) (*PressEqualsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PressEquals not implemented")
}
func (UnimplementedCommandServiceServer) PressClear(context.Context, *PressClearRequest) (*PressClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PressClear not implemented")
}
func (UnimplementedCommandServiceServer) PressUndo(context.Context, *PressUndoRequest) (*PressUndoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PressUndo not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_PressDigit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressDigitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).PressDigit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_PressDigit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).PressDigit(ctx, req.(*PressDigitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_PressOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).PressOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_PressOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).PressOperator(ctx, req.(*PressOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_PressEquals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressEqualsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).PressEquals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_PressEquals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).PressEquals(ctx, req.(*PressEqualsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_PressClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).PressClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_PressClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).PressClear(ctx, req.(*PressClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_PressUndo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressUndoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).PressUndo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_PressUndo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).PressUndo(ctx, req.(*PressUndoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.v1.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PressDigit",
			Handler:    _CommandService_PressDigit_Handler,
		},
		{
			MethodName: "PressOperator",
			Handler:    _CommandService_PressOperator_Handler,
		},
		{
			MethodName: "PressEquals",
			Handler:    _CommandService_PressEquals_Handler,
		},
		{
			MethodName: "PressClear",
			Handler:    _CommandService_PressClear_Handler,
		},
		{
			MethodName: "PressUndo",
			Handler:    _CommandService_PressUndo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc/v1/write_service.proto",
}

const (
	EventStreamService_Subscribe_FullMethodName = "/calc.v1.EventStreamService/Subscribe"
)

// EventStreamServiceClient is the client API for EventStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStreamServiceClient interface {
	Subscribe(ctx context.Context, in *EventStreamServiceSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventStreamServiceSubscribeResponse], error)
}

type eventStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamServiceClient(cc grpc.ClientConnInterface) EventStreamServiceClient {
	return &eventStreamServiceClient{cc}
}

func (c *eventStreamServiceClient) Subscribe(ctx context.Context, in *EventStreamServiceSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventStreamServiceSubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStreamService_ServiceDesc.Streams[0], EventStreamService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventStreamServiceSubscribeRequest, EventStreamServiceSubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStreamService_SubscribeClient = grpc.ServerStreamingClient[EventStreamServiceSubscribeResponse]

// EventStreamServiceServer is the server API for EventStreamService service.
// All implementations must embed UnimplementedEventStreamServiceServer
// for forward compatibility.
type EventStreamServiceServer interface {
	Subscribe(*EventStreamServiceSubscribeRequest, grpc.ServerStreamingServer[EventStreamServiceSubscribeResponse]) error
	mustEmbedUnimplementedEventStreamServiceServer()
}

// UnimplementedEventStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamServiceServer struct{}

func (UnimplementedEventStreamServiceServer) Subscribe(*EventStreamServiceSubscribeRequest, grpc.ServerStreamingServer[EventStreamServiceSubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventStreamServiceServer) mustEmbedUnimplementedEventStreamServiceServer() {}
func (UnimplementedEventStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeEventStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamServiceServer will
// result in compilation errors.
type UnsafeEventStreamServiceServer interface {
	mustEmbedUnimplementedEventStreamServiceServer()
}

func RegisterEventStreamServiceServer(s grpc.ServiceRegistrar, srv EventStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedEventStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStreamService_ServiceDesc, srv)
}

func _EventStreamService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventStreamServiceSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServiceServer).Subscribe(m, &grpc.GenericServerStream[EventStreamServiceSubscribeRequest, EventStreamServiceSubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStreamService_SubscribeServer = grpc.ServerStreamingServer[EventStreamServiceSubscribeResponse]

// EventStreamService_ServiceDesc is the grpc.ServiceDesc for EventStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.v1.EventStreamService",
	HandlerType: (*EventStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EventStreamService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calc/v1/write_service.proto",
}

const (
	EventHistoryService_ListEvents_FullMethodName = "/calc.v1.EventHistoryService/ListEvents"
)

// EventHistoryServiceClient is the client API for EventHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventHistoryServiceClient interface {
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListEventsResponse], error)
}

type eventHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventHistoryServiceClient(cc grpc.ClientConnInterface) EventHistoryServiceClient {
	return &eventHistoryServiceClient{cc}
}

func (c *eventHistoryServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventHistoryService_ServiceDesc.Streams[0], EventHistoryService_ListEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListEventsRequest, ListEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventHistoryService_ListEventsClient = grpc.ServerStreamingClient[ListEventsResponse]

// EventHistoryServiceServer is the server API for EventHistoryService service.
// All implementations must embed UnimplementedEventHistoryServiceServer
// for forward compatibility.
type EventHistoryServiceServer interface {
	ListEvents(*ListEventsRequest, grpc.ServerStreamingServer[ListEventsResponse]) error
	mustEmbedUnimplementedEventHistoryServiceServer()
}

// UnimplementedEventHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventHistoryServiceServer struct{}

func (UnimplementedEventHistoryServiceServer) ListEvents(*ListEventsRequest, grpc.ServerStreamingServer[ListEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventHistoryServiceServer) mustEmbedUnimplementedEventHistoryServiceServer() {}
func (UnimplementedEventHistoryServiceServer) testEmbeddedByValue()                             {}

// UnsafeEventHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventHistoryServiceServer will
// result in compilation errors.
type UnsafeEventHistoryServiceServer interface {
	mustEmbedUnimplementedEventHistoryServiceServer()
}

func RegisterEventHistoryServiceServer(s grpc.ServiceRegistrar, srv EventHistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedEventHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventHistoryService_ServiceDesc, srv)
}

func _EventHistoryService_ListEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventHistoryServiceServer).ListEvents(m, &grpc.GenericServerStream[ListEventsRequest, ListEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventHistoryService_ListEventsServer = grpc.ServerStreamingServer[ListEventsResponse]

// EventHistoryService_ServiceDesc is the grpc.ServiceDesc for EventHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calc.v1.EventHistoryService",
	HandlerType: (*EventHistoryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEvents",
			Handler:       _EventHistoryService_ListEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calc/v1/write_service.proto",
}
