// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: calc/v1/write_service.proto

package calcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PressDigitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digit         string                 `protobuf:"bytes,1,opt,name=digit,proto3" json:"digit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressDigitRequest) Reset() {
	*x = PressDigitRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressDigitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressDigitRequest) ProtoMessage() {}

func (x *PressDigitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressDigitRequest.ProtoReflect.Descriptor instead.
func (*PressDigitRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{0}
}

func (x *PressDigitRequest) GetDigit() string {
	if x != nil {
		return x.Digit
	}
	return ""
}

type PressDigitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressDigitResponse) Reset() {
	*x = PressDigitResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressDigitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressDigitResponse) ProtoMessage() {}

func (x *PressDigitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressDigitResponse.ProtoReflect.Descriptor instead.
func (*PressDigitResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{1}
}

type PressOperatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressOperatorRequest) Reset() {
	*x = PressOperatorRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressOperatorRequest) ProtoMessage() {}

func (x *PressOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressOperatorRequest.ProtoReflect.Descriptor instead.
func (*PressOperatorRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{2}
}

func (x *PressOperatorRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type PressOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressOperatorResponse) Reset() {
	*x = PressOperatorResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressOperatorResponse) ProtoMessage() {}

func (x *PressOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressOperatorResponse.ProtoReflect.Descriptor instead.
func (*PressOperatorResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{3}
}

type PressEqualsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressEqualsRequest) Reset() {
	*x = PressEqualsRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressEqualsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressEqualsRequest) ProtoMessage() {}

func (x *PressEqualsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressEqualsRequest.ProtoReflect.Descriptor instead.
func (*PressEqualsRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{4}
}

type PressEqualsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressEqualsResponse) Reset() {
	*x = PressEqualsResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressEqualsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressEqualsResponse) ProtoMessage() {}

func (x *PressEqualsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressEqualsResponse.ProtoReflect.Descriptor instead.
func (*PressEqualsResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{5}
}

type PressClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressClearRequest) Reset() {
	*x = PressClearRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressClearRequest) ProtoMessage() {}

func (x *PressClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressClearRequest.ProtoReflect.Descriptor instead.
func (*PressClearRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{6}
}

type PressClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressClearResponse) Reset() {
	*x = PressClearResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressClearResponse) ProtoMessage() {}

func (x *PressClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressClearResponse.ProtoReflect.Descriptor instead.
func (*PressClearResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{7}
}

type PressUndoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressUndoRequest) Reset() {
	*x = PressUndoRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressUndoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressUndoRequest) ProtoMessage() {}

func (x *PressUndoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressUndoRequest.ProtoReflect.Descriptor instead.
func (*PressUndoRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{8}
}

type PressUndoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressUndoResponse) Reset() {
	*x = PressUndoResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressUndoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressUndoResponse) ProtoMessage() {}

func (x *PressUndoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressUndoResponse.ProtoReflect.Descriptor instead.
func (*PressUndoResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{9}
}

type EventStreamServiceSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersistenceId string                 `protobuf:"bytes,1,opt,name=persistence_id,json=persistenceId,proto3" json:"persistence_id,omitempty"`
	FromSeqNr     int64                  `protobuf:"varint,2,opt,name=from_seq_nr,json=fromSeqNr,proto3" json:"from_seq_nr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamServiceSubscribeRequest) Reset() {
	*x = EventStreamServiceSubscribeRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamServiceSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamServiceSubscribeRequest) ProtoMessage() {}

func (x *EventStreamServiceSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamServiceSubscribeRequest.ProtoReflect.Descriptor instead.
func (*EventStreamServiceSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{10}
}

func (x *EventStreamServiceSubscribeRequest) GetPersistenceId() string {
	if x != nil {
		return x.PersistenceId
	}
	return ""
}

func (x *EventStreamServiceSubscribeRequest) GetFromSeqNr() int64 {
	if x != nil {
		return x.FromSeqNr
	}
	return 0
}

type EventStreamServiceSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *EventEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamServiceSubscribeResponse) Reset() {
	*x = EventStreamServiceSubscribeResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamServiceSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamServiceSubscribeResponse) ProtoMessage() {}

func (x *EventStreamServiceSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamServiceSubscribeResponse.ProtoReflect.Descriptor instead.
func (*EventStreamServiceSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{11}
}

func (x *EventStreamServiceSubscribeResponse) GetEnvelope() *EventEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersistenceId string                 `protobuf:"bytes,1,opt,name=persistence_id,json=persistenceId,proto3" json:"persistence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_calc_v1_write_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListEventsRequest) GetPersistenceId() string {
	if x != nil {
		return x.PersistenceId
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *EventEnvelope         `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_calc_v1_write_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_v1_write_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_calc_v1_write_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListEventsResponse) GetEnvelope() *EventEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_calc_v1_write_service_proto protoreflect.FileDescriptor

const file_calc_v1_write_service_proto_rawDesc = "" +
	"\n" +
	"\x1bcalc/v1/write_service.proto\x12\acalc.v1\x1a\x14calc/v1/events.proto\")\n" +
	"\x11PressDigitRequest\x12\x14\n" +
	"\x05digit\x18\x01 \x01(\tR\x05digit\"\x14\n" +
	"\x12PressDigitResponse\"2\n" +
	"\x14PressOperatorRequest\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\"\x17\n" +
	"\x15PressOperatorResponse\"\x14\n" +
	"\x12PressEqualsRequest\"\x15\n" +
	"\x13PressEqualsResponse\"\x13\n" +
	"\x11PressClearRequest\"\x14\n" +
	"\x12PressClearResponse\"\x12\n" +
	"\x10PressUndoRequest\"\x13\n" +
	"\x11PressUndoResponse\"k\n" +
	"\"EventStreamServiceSubscribeRequest\x12%\n" +
	"\x0epersistence_id\x18\x01 \x01(\tR\rpersistenceId\x12\x1e\n" +
	"\vfrom_seq_nr\x18\x02 \x01(\x03R\tfromSeqNr\"Y\n" +
	"#EventStreamServiceSubscribeResponse\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.calc.v1.EventEnvelopeR\benvelope\":\n" +
	"\x11ListEventsRequest\x12%\n" +
	"\x0epersistence_id\x18\x01 \x01(\tR\rpersistenceId\"H\n" +
	"\x12ListEventsResponse\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.calc.v1.EventEnvelopeR\benvelope2\xfc\x02\n" +
	"\x0eCommandService\x12E\n" +
	"\n" +
	"PressDigit\x12\x1a.calc.v1.PressDigitRequest\x1a\x1b.calc.v1.PressDigitResponse\x12N\n" +
	"\rPressOperator\x12\x1d.calc.v1.PressOperatorRequest\x1a\x1e.calc.v1.PressOperatorResponse\x12H\n" +
	"\vPressEquals\x12\x1b.calc.v1.PressEqualsRequest\x1a\x1c.calc.v1.PressEqualsResponse\x12E\n" +
	"\n" +
	"PressClear\x12\x1a.calc.v1.PressClearRequest\x1a\x1b.calc.v1.PressClearResponse\x12B\n" +
	"\tPressUndo\x12\x19.calc.v1.PressUndoRequest\x1a\x1a.calc.v1.PressUndoResponse2~\n" +
	"\x12EventStreamService\x12h\n" +
	"\tSubscribe\x12+.calc.v1.EventStreamServiceSubscribeRequest\x1a,.calc.v1.EventStreamServiceSubscribeResponse0\x012^\n" +
	"\x13EventHistoryService\x12G\n" +
	"\n" +
	"ListEvents\x12\x1a.calc.v1.ListEventsRequest\x1a\x1b.calc.v1.ListEventsResponse0\x01B(Z&dentaku-bff/internal/pb/calc/v1;calcv1b\x06proto3"

var (
	file_calc_v1_write_service_proto_rawDescOnce sync.Once
	file_calc_v1_write_service_proto_rawDescData []byte
)

func file_calc_v1_write_service_proto_rawDescGZIP() []byte {
	file_calc_v1_write_service_proto_rawDescOnce.Do(func() {
		file_calc_v1_write_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calc_v1_write_service_proto_rawDesc), len(file_calc_v1_write_service_proto_rawDesc)))
	})
	return file_calc_v1_write_service_proto_rawDescData
}

var file_calc_v1_write_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_calc_v1_write_service_proto_goTypes = []any{
	(*PressDigitRequest)(nil),                   // 0: calc.v1.PressDigitRequest
	(*PressDigitResponse)(nil),                  // 1: calc.v1.PressDigitResponse
	(*PressOperatorRequest)(nil),                // 2: calc.v1.PressOperatorRequest
	(*PressOperatorResponse)(nil),               // 3: calc.v1.PressOperatorResponse
	(*PressEqualsRequest)(nil),                  // 4: calc.v1.PressEqualsRequest
	(*PressEqualsResponse)(nil),                 // 5: calc.v1.PressEqualsResponse
	(*PressClearRequest)(nil),                   // 6: calc.v1.PressClearRequest
	(*PressClearResponse)(nil),                  // 7: calc.v1.PressClearResponse
	(*PressUndoRequest)(nil),                    // 8: calc.v1.PressUndoRequest
	(*PressUndoResponse)(nil),                   // 9: calc.v1.PressUndoResponse
	(*EventStreamServiceSubscribeRequest)(nil),  // 10: calc.v1.EventStreamServiceSubscribeRequest
	(*EventStreamServiceSubscribeResponse)(nil), // 11: calc.v1.EventStreamServiceSubscribeResponse
	(*ListEventsRequest)(nil),                   // 12: calc.v1.ListEventsRequest
	(*ListEventsResponse)(nil),                  // 13: calc.v1.ListEventsResponse
	(*EventEnvelope)(nil),                       // 14: calc.v1.EventEnvelope
}
var file_calc_v1_write_service_proto_depIdxs = []int32{
	14, // 0: calc.v1.EventStreamServiceSubscribeResponse.envelope:type_name -> calc.v1.EventEnvelope
	14, // 1: calc.v1.ListEventsResponse.envelope:type_name -> calc.v1.EventEnvelope
	0,  // 2: calc.v1.CommandService.PressDigit:input_type -> calc.v1.PressDigitRequest
	2,  // 3: calc.v1.CommandService.PressOperator:input_type -> calc.v1.PressOperatorRequest
	4,  // 4: calc.v1.CommandService.PressEquals:input_type -> calc.v1.PressEqualsRequest
	6,  // 5: calc.v1.CommandService.PressClear:input_type -> calc.v1.PressClearRequest
	8,  // 6: calc.v1.CommandService.PressUndo:input_type -> calc.v1.PressUndoRequest
	10, // 7: calc.v1.EventStreamService.Subscribe:input_type -> calc.v1.EventStreamServiceSubscribeRequest
	12, // 8: calc.v1.EventHistoryService.ListEvents:input_type -> calc.v1.ListEventsRequest
	1,  // 9: calc.v1.CommandService.PressDigit:output_type -> calc.v1.PressDigitResponse
	3,  // 10: calc.v1.CommandService.PressOperator:output_type -> calc.v1.PressOperatorResponse
	5,  // 11: calc.v1.CommandService.PressEquals:output_type -> calc.v1.PressEqualsResponse
	7,  // 12: calc.v1.CommandService.PressClear:output_type -> calc.v1.PressClearResponse
	9,  // 13: calc.v1.CommandService.PressUndo:output_type -> calc.v1.PressUndoResponse
	11, // 14: calc.v1.EventStreamService.Subscribe:output_type -> calc.v1.EventStreamServiceSubscribeResponse
	13, // 15: calc.v1.EventHistoryService.ListEvents:output_type -> calc.v1.ListEventsResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_calc_v1_write_service_proto_init() }
func file_calc_v1_write_service_proto_init() {
	if File_calc_v1_write_service_proto != nil {
		return
	}
	file_calc_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calc_v1_write_service_proto_rawDesc), len(file_calc_v1_write_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_calc_v1_write_service_proto_goTypes,
		DependencyIndexes: file_calc_v1_write_service_proto_depIdxs,
		MessageInfos:      file_calc_v1_write_service_proto_msgTypes,
	}.Build()
	File_calc_v1_write_service_proto = out.File
	file_calc_v1_write_service_proto_goTypes = nil
	file_calc_v1_write_service_proto_depIdxs = nil
}
