package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"dentaku-bff/graph/model"
	"fmt"
	"encoding/json"
	"net/http"
	"bytes"
)

// ==========================================
// 🚀 Scala Write サーバーへコマンドを横流しするヘルパー関数
// ==========================================
func sendCommandToScala(path string, payload map[string]string) error {
	url := "http://localhost:9000/command" + path
	var jsonValue []byte
	if payload != nil {
		jsonValue, _ = json.Marshal(payload)
	}

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonValue))
	if err != nil {
		return fmt.Errorf("failed to call Scala server: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusAccepted {
		return fmt.Errorf("Scala server returned status: %d", resp.StatusCode)
	}
	return nil
}

func (r *mutationResolver) PressDigit(ctx context.Context, digit string) (bool, error) {
	err := sendCommandToScala("/digit", map[string]string{"digit": digit})
	return err == nil, err
}

func (r *mutationResolver) PressOperator(ctx context.Context, operator string) (bool, error) {
	err := sendCommandToScala("/operator", map[string]string{"operator": operator})
	return err == nil, err
}

func (r *mutationResolver) PressEquals(ctx context.Context) (bool, error) {
	err := sendCommandToScala("/equals", nil)
	return err == nil, err
}

func (r *mutationResolver) PressClear(ctx context.Context) (bool, error) {
	err := sendCommandToScala("/clear", nil)
	return err == nil, err
}


// Undo is the resolver for the undo field.
func (r *mutationResolver) Undo(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Undo - undo"))
}

// CurrentState は現在の状態を返します。
func (r *queryResolver) CurrentState(ctx context.Context) (*model.CalculatorState, error) {
	r.Mu.Lock()
	defer r.Mu.Unlock()
	return r.State, nil
}

// EventHistory is the resolver for the eventHistory field.
func (r *queryResolver) EventHistory(ctx context.Context) ([]model.CalcEvent, error) {
	panic(fmt.Errorf("not implemented: EventHistory - eventHistory"))
}

// StateUpdated is the resolver for the stateUpdated field.
func (r *subscriptionResolver) StateUpdated(ctx context.Context) (<-chan *model.CalculatorState, error) {
	r.Mu.Lock()
	defer r.Mu.Unlock()

	// 1. クライアント専用のチャネルを作成（バッファサイズ1を持たせる）
	ch := make(chan *model.CalculatorState, 1)

	// 2. クライアントを識別する一意のIDを生成（今回は簡単のため UUID の代わりに番地などを使用）
	id := fmt.Sprintf("%p", ch)
	r.Subscribers[id] = ch

	// 3. コネクションが切断されたときのクリーンアップ処理を登録
	go func() {
		<-ctx.Done()
		r.Mu.Lock()
		defer r.Mu.Unlock()
		delete(r.Subscribers, id)
		close(ch)
	}()

	// 4. サブスクライブ直後に、現在の状態を1回 Push しておく（UX向上のため）
	stateCopy := &model.CalculatorState{
		DisplayValue: r.State.DisplayValue,
		StoredValue:  r.State.StoredValue,
		CurrentOp:    r.State.CurrentOp,
		IsNewInput:   r.State.IsNewInput,
	}
	ch <- stateCopy

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
