package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"dentaku-bff/graph/model"
	"fmt"
	"encoding/json"
	"net/http"
	"bytes"
	"time"
)

func fetchStateFromReadServer() (*model.CalculatorState, error) {
	resp, err := http.Get("http://localhost:9001/state")
	if err != nil {
		return nil, fmt.Errorf("failed to call Read server: %v", err)
	}
	defer resp.Body.Close()

	var data struct {
		DisplayValue string `json:"displayValue"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return nil, err
	}

	// 画面表示に必要な displayValue だけを Read サーバーから取得して返す
	return &model.CalculatorState{
		DisplayValue: data.DisplayValue,
	}, nil
}

// ==========================================
// 🚀 Scala Write サーバーへコマンドを横流しするヘルパー関数
// ==========================================
func sendCommandToScala(path string, payload map[string]string) error {
	url := "http://localhost:9000/command" + path
	var jsonValue []byte
	if payload != nil {
		jsonValue, _ = json.Marshal(payload)
	}

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonValue))
	if err != nil {
		return fmt.Errorf("failed to call Scala server: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusAccepted {
		return fmt.Errorf("Scala server returned status: %d", resp.StatusCode)
	}
	return nil
}

func (r *mutationResolver) PressDigit(ctx context.Context, digit string) (bool, error) {
	err := sendCommandToScala("/digit", map[string]string{"digit": digit})
	return err == nil, err
}

func (r *mutationResolver) PressOperator(ctx context.Context, operator string) (bool, error) {
	err := sendCommandToScala("/operator", map[string]string{"operator": operator})
	return err == nil, err
}

func (r *mutationResolver) PressEquals(ctx context.Context) (bool, error) {
	err := sendCommandToScala("/equals", nil)
	return err == nil, err
}

func (r *mutationResolver) PressClear(ctx context.Context) (bool, error) {
	err := sendCommandToScala("/clear", nil)
	return err == nil, err
}


// Undo is the resolver for the undo field.
func (r *mutationResolver) Undo(ctx context.Context) (bool, error) {
	// panic(fmt.Errorf("not implemented: Undo - undo"))
	return false, nil // 今回は Mock なので nil を返しておく
}

// CurrentState は現在の状態を返します。
func (r *queryResolver) CurrentState(ctx context.Context) (*model.CalculatorState, error) {
	return fetchStateFromReadServer()
}

// EventHistory is the resolver for the eventHistory field.
func (r *queryResolver) EventHistory(ctx context.Context) ([]model.CalcEvent, error) {
	return nil, nil
}

// StateUpdated is the resolver for the stateUpdated field.
func (r *subscriptionResolver) StateUpdated(ctx context.Context) (<-chan *model.CalculatorState, error) {
	ch := make(chan *model.CalculatorState, 1)

	go func() {
		defer close(ch)
		var lastVal string
		
		// 0.5秒に1回、Readサーバーへ最新状態をポーリング（監視）しにいく
		ticker := time.NewTicker(500 * time.Millisecond)
		defer ticker.Stop()

		// 接続時の一発目
		if initial, err := fetchStateFromReadServer(); err == nil {
			lastVal = initial.DisplayValue
			ch <- initial
		}

		for {
			select {
			case <-ctx.Done(): // クライアント(React)が切断した時
				return
			case <-ticker.C:
				state, err := fetchStateFromReadServer()
				// 前回から値が変わっていたら React にプッシュ通知！
				if err == nil && state.DisplayValue != lastVal {
					lastVal = state.DisplayValue
					ch <- state
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
