package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"dentaku-bff/graph/model"
	calcv1 "dentaku-bff/internal/pb/calc/v1"
	"io"
)

// PressDigit is the resolver for the pressDigit field.
func (r *mutationResolver) PressDigit(ctx context.Context, digit string) (bool, error) {
	_, err := r.WriteCommand.PressDigit(ctx, &calcv1.PressDigitRequest{Digit: digit})
	return err == nil, err
}

// PressOperator is the resolver for the pressOperator field.
func (r *mutationResolver) PressOperator(ctx context.Context, operator string) (bool, error) {
	_, err := r.WriteCommand.PressOperator(ctx, &calcv1.PressOperatorRequest{Operator: operator})
	return err == nil, err
}

// PressEquals is the resolver for the pressEquals field.
func (r *mutationResolver) PressEquals(ctx context.Context) (bool, error) {
	_, err := r.WriteCommand.PressEquals(ctx, &calcv1.PressEqualsRequest{})
	return err == nil, err
}

// PressClear is the resolver for the pressClear field.
func (r *mutationResolver) PressClear(ctx context.Context) (bool, error) {
	_, err := r.WriteCommand.PressClear(ctx, &calcv1.PressClearRequest{})
	return err == nil, err
}

// Undo is the resolver for the undo field.
func (r *mutationResolver) Undo(ctx context.Context) (bool, error) {
	_, err := r.WriteCommand.PressUndo(ctx, &calcv1.PressUndoRequest{})
	return err == nil, err
}

// CurrentState is the resolver for the currentState field.
func (r *queryResolver) CurrentState(ctx context.Context) (*model.CalculatorState, error) {
	resp, err := r.ReadQuery.GetState(ctx, &calcv1.GetStateRequest{})
	if err != nil {
		return nil, err
	}
	return toGqlState(resp.GetState()), nil
}

// EventHistory is the resolver for the eventHistory field.
func (r *queryResolver) EventHistory(ctx context.Context) ([]model.CalcEvent, error) {
	stream, err := r.WriteHistory.ListEvents(ctx, &calcv1.ListEventsRequest{
		PersistenceId: r.PersistenceID,
	})
	if err != nil {
		return nil, err
	}
	events := make([]model.CalcEvent, 0)
	for {
		resp, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if gqlEvt := envelopeToGqlEvent(resp.GetEnvelope()); gqlEvt != nil {
			events = append(events, gqlEvt)
		}
	}
	return events, nil
}

// StateUpdated is the resolver for the stateUpdated field.
func (r *subscriptionResolver) StateUpdated(ctx context.Context) (<-chan *model.CalculatorState, error) {
	stream, err := r.ReadStream.Subscribe(ctx, &calcv1.StateStreamServiceSubscribeRequest{})
	if err != nil {
		return nil, err
	}

	ch := make(chan *model.CalculatorState, 16)
	go func() {
		defer close(ch)
		for {
			resp, err := stream.Recv()
			if err != nil {
				return
			}
			select {
			case ch <- toGqlState(resp.GetState()):
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
